<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>

<h1>Login</h1>

<?php if (!empty($flash)): ?>
    <p style="color: red"><?= $flash['error'][0]?></p>
<?php endif; ?>

<form action="/session" method="post">
    <input type="text" name="email" value="<?= htmlspecialchars($email) ?>">
    <input type="submit" value="login">
</form>

</body>
</html>