<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>New User</title>
</head>
<body>

<h1>Add new user</h1>

<form action="/users" method="post">
    <div>
        <input type="text" name="user[nickname]" id="nickname">
        <label for="nickname">Nickname</label>
    </div>
    <div>
        <input type="text" name="user[email]" id="email">
        <label for="email">Email</label>
    </div>
    <div>
        <input type="submit" value="Create">
    </div>
</form>

</body>
</html>