<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>New User</title>
</head>
<body>

<h1>Add new user</h1>

<form action="/users" method="post">
    <div>
        <input type="text" name="user[nickname]" id="nickname" value="<?= htmlspecialchars($userData['nickname'] ?? '') ?>" required>
        <label for="nickname">Nickname</label>
    </div>
    <?php if (isset($errors['nickname'])): ?>
        <div style="font-size: 12px; color: red;"><?= $errors['nickname'] ?></div>
    <?php endif ?>
    <div>
        <input type="text" name="user[email]" id="email" value="<?= htmlspecialchars($userData['email'] ?? '') ?>" required>
        <label for="email">Email</label>
    </div>
    <?php if (isset($errors['email'])): ?>
        <div style="font-size: 12px; color: red;"><?= $errors['email'] ?></div>
    <?php endif ?>
    <div>
        <input type="submit" value="Create">
    </div>
</form>

<p><a href="/users">Back to users</a></p>

</body>
</html>