<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Show user</title>
</head>
<body>

<h1>Hello, <?= htmlspecialchars($id) ?></h1>
<h2>Your nickname is <?= htmlspecialchars($nickname) ?></h2>

</body>
</html>

